name: KG-RAG-Prototype
services:
  lightrag:
    container_name: lightrag
    image: lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - lightrag:latest
    ports:
      - "${PORT:-9621}:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - ./config.ini:/app/config.ini
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ollama:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - data:/root/.ollama
        ports:
            - 11434:11434
        container_name: ollama
        restart: unless-stopped
        image: ollama/ollama:latest
volumes:
    data:
        external: false
        name: ollama-data